# Artificial Neural Network -- Multilayer Perceptron

Here we use the cancer dataset to learn logistic regression.

## Dataset -- XOr

In [58]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split


In [59]:
values = np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]])
data_xor = pd.DataFrame(columns=['x1','x2','y'],data=values)
data_xor

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

# Multilayer Perceptron

In [80]:
theta1 = np.random.uniform(size=(3,5))
theta2 = np.random.uniform(size=(6,3))
theta3 = np.random.uniform(size=(4,1))
theta = np.array([theta1, theta2, theta3])
for i, sub_theta in enumerate(theta):
    print(sub_theta)

[[0.32905723 0.78301265 0.25390672 0.28117744 0.08947143]
 [0.13231167 0.44219862 0.8811684  0.26193801 0.75705985]
 [0.03338576 0.06859136 0.51859611 0.19969068 0.47042142]]
[[0.36760906 0.16520794 0.14432369]
 [0.84077053 0.37936009 0.5985514 ]
 [0.01154015 0.27412383 0.78737755]
 [0.71421145 0.42626674 0.85294844]
 [0.84172348 0.60116617 0.32583081]
 [0.47945393 0.56618974 0.90213317]]
[[0.82942478]
 [0.98400761]
 [0.09195518]
 [0.30792469]]


In [81]:
X=data_xor[['x1','x2']]

In [90]:
def add_ones(X):
    ones=np.ones((X.shape[0],1))
    X_with_ones=np.hstack((ones, X))
    return X_with_ones

In [91]:
def mlp_model(theta, X):
    n_layers = len(theta)
    layers = [X]
    for i, sub_theta in enumerate(theta):
        print(i)
        
        #print(sub_theta.shape)
        X = add_ones(X)
        print(X.shape)
        z = np.matmul(X, sub_theta)
        #print("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz")
        #print(z)
        s = sigmoid(z)
        X = s
        layers.append(X)
    y=X
    #print(layers)
    #print(y)
    return layers

In [94]:
layers=mlp_model(theta,X)

0
(4, 3)
1
(4, 6)
2
(4, 4)


In [104]:
def mlp_optimize(theta,X,y):
    n = X.shape[0]
    n_theta = theta.shape[0]
    alpha = 1e-1

    layers = mlp_model(theta,X)
    X_all = layers[:-1]
    Y_all = layers[1:]
    for X, y_hat in zip(X_all, Y_all):
        delta_y=y_hat-y
        print(delta_y)
        dtheta = (1.0/n) * ((y_hat-y)*add_ones(X))
        dtheta = np.sum(dtheta, axis=0)
        dtheta = dtheta.reshape((n_theta,1))
        theta = theta - alpha * dtheta
    return theta

In [105]:
mlp_optimize(theta, X, y)

0
(4, 3)
1
(4, 6)
2
(4, 4)
[[ 0.58152997  0.68632905  0.56313784  0.56983487  0.52235295]
 [-0.41036832 -0.29909649 -0.31593794 -0.38204715 -0.36357225]
 [-0.38666113 -0.22702066 -0.24322572 -0.36746315 -0.30016101]
 [ 0.62122587  0.78479013  0.83938661  0.67760918  0.78867427]]


ValueError: operands could not be broadcast together with shapes (4,5) (4,3) 

# Use sklearn

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
X = data_xor[['x1','x2']]
y = np.array(data_xor['y']).reshape((4,1))

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(4,4), max_iter=2000, alpha=0.01, activation='relu')
mlp.fit(X, y)

In [ ]:
mlp.score(X,y)

In [ ]:
mlp.predict(X)

In [ ]:
y