under development

In [ ]:
import numpy as np

In [3]:
def sigmoid(Z):
    Z = np.array(Z)
    return 1 / (1 + np.exp(-Z))

In [8]:
X=np.array([[1,1],[1,0],[0,1],[0,0]])
y=np.array([0,1,1,0])

In [9]:
Z = np.array([1,2,3])

In [10]:
W1 = np.zeros((2,2))
B1 = np.zeros((2,))

W2 = np.zeros((2, 1))
B2 = 0

In [11]:
def model(X, W1, B1, W2, B2):
    Z1 = np.dot(X, W1) + B1
    A1 = sigmoid(Z1)
    print(A1)
    Z2 = np.dot(A1, W2) + B2
    print(Z2)
    A2 = sigmoid(Z2)
    
    return A2

In [12]:
model(X, W1, B1, W2, B2)

[[0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]]
[[0.]
 [0.]
 [0.]
 [0.]]


array([[0.5],
       [0.5],
       [0.5],
       [0.5]])

In [38]:
A = []
A.append(X)
A.append(np.array([1,1]))
A.append(0)
A = np.array(A)

In [58]:
A = {}
A[1] = X
A[2] = np.array([0.1,0.11])
A[3] = 0

W = {}
W[1] = np.array([[0.1, 0.11], [0.12, 0.13]])
W[2] = np.array([0.1, 0.11]).reshape((2,1))

B = {}
B[1] = np.array([0.11, 0.12])
B[2] = np.array(0.11)

Z = {}
Z[2] = np.array([0.1,0.11])
Z[3] = 0

In [59]:
def forward_propagate(A, Z, W, B):
    Z[2] = np.dot(A[1], W[1]) + B[1]
    A[2] = sigmoid(Z[2])
    Z[3] = np.dot(A[2], W[2]) + B[2]
    A[3] = sigmoid(Z[3])
    return A, Z, W, B

In [60]:
A, Z, W, B = forward_propagate(A, Z, W, B)

In [61]:
A, Z, W, B

({1: array([[1, 1],
         [1, 0],
         [0, 1],
         [0, 0]]),
  2: array([[0.58175938, 0.58904043],
         [0.55230791, 0.55724785],
         [0.55724785, 0.5621765 ],
         [0.5274723 , 0.52996405]]),
  3: array([[0.55798059],
         [0.55639108],
         [0.5566468 ],
         [0.55503691]])},
 {2: array([[0.33, 0.36],
         [0.21, 0.23],
         [0.23, 0.25],
         [0.11, 0.12]]),
  3: array([[0.23297039],
         [0.22652805],
         [0.2275642 ],
         [0.22104328]])},
 {1: array([[0.1 , 0.11],
         [0.12, 0.13]]),
  2: array([[0.1 ],
         [0.11]])},
 {1: array([0.11, 0.12]), 2: array(0.11)})

In [73]:
D={}
D[3] = A[3].T - y
D[3] = D[3].reshape((4,1))
D[2] = np.multiply(np.dot(D[3], W[2].T), np.multiply(A[2], 1-A[2]))

In [74]:
D

{3: array([[ 0.55798059],
        [-0.44360892],
        [-0.4433532 ],
        [ 0.55503691]]),
 2: array([[ 0.01357653,  0.01485785],
        [-0.01096885, -0.01203932],
        [-0.01093853, -0.01200368],
        [ 0.01383403,  0.0152087 ]])}

In [75]:
np.dot(W[2], D[3].T)

array([[ 0.05579806, -0.04436089, -0.04433532,  0.05550369],
       [ 0.06137787, -0.04879698, -0.04876885,  0.06105406]])

In [69]:
np.multiply(A[2], 1-A[2])

array([[0.2433154 , 0.2420718 ],
       [0.24726388, 0.24672268],
       [0.24672268, 0.24613408],
       [0.24924527, 0.24910216]])

In [39]:
W = []
W.append(np.array([[0.1, 0.11], [0.12, 0.13]]))
W.append(np.array([[0.111, 0.112]]))
W = np.array(W)

In [40]:
B = []
B.append(np.array([[0.1, 0.11]]))
B.append(np.array([[0.111, 0.112]]))
B = np.array(B)

In [41]:
Z = []
Z.append(np.array([1, 1, 1, 1]))
Z.append(np.array([1, 1,]))
Z.append(0)

In [32]:
np.dot(X,X.T)

array([[2, 1, 1, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0]])

In [33]:
def cross_entropy(y, y_hat):
    n_samples = y.shape[0]
    return sum(-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))/n_samples

In [34]:
def cost_function(X, y, W1, B1, W2, B2):
    y_hat = model(X,  W1, B1, W2, B2)
    return cross_entropy(y, y_hat)

In [35]:
def transfer_derivative(A):
    return A * (1-A)

SyntaxError: unexpected EOF while parsing (<ipython-input-36-0f02a54d350e>, line 1)